---

- name: create ec2 instance
  hosts: localhost
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2:
        region: us-east-1
        key_name: vbr-keypair
        instance_type: t2.micro
        image: ami-08e4e35cccc6189f4
        wait: yes
        count: 1
