---

- name: stop nginx docker container
  hosts: server1
  tasks:
    - name: run nginx as docker container
      community.docker.docker_container:
        name: nginx-as-docker-container
        state: stopped
