---

- name: uninstall argocd from kubernetes
  hosts: localhost
  tasks:

    - name: uninstall argocd
      kubernetes.core.k8s:
        src: src/argocd.yml
        namespace: argocd
        state: absent

    - name: remove namespace
      kubernetes.core.k8s:
        name: argocd
        kind: namespace
        state: absent

