---

- hosts: localhost
  tasks:
    - name: clone git repo
      ansible.builtin.git:
        repo: https://github.com/vbrsid/simpleweb.git
        dest: ./src/testing
        single_branch: yes
        version: master
