---
- name: Install docker on Ubuntu 20.04
  hosts: server
  tasks:    

    - name: Get docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker
        mode: 0600
    
    - name: Update the packages cache
      apt: 
        update_cache: yes

    - name: Install Docker
      apt: 
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start Docker Service
      service: 
        name: docker
        state: started
        enabled: yes
